### PR TITLE
Add config options and setup instructions

### PR DESCRIPTION
**Pull request by kevin51jiang**
Love this template! Simple enough to use, and the design is nice as well.

I wanted to use it for myself, so I made a few changes that make it easy for other people to change the configuration. There should be no *actual* text changes, except where in a few spots I changed it from `(c) 2022` to `(c) ${getCurrentYear()}`.

I also added setup instructions so other people can quickly get setup.

### CODE REVIEW

**Comment by leebyron** [comment]
This is great!

Small suggestions:

- copyright should be from the time stamp of the source markdown doc being generated
- Config is great, but rather than putting in first/last, instead allow full configuration of the title text and other content fields
- would you be okay including a designed by Lee Byron link in the footer that links back to the original? It could help others find this tool

**Comment by kevin51jiang** [comment]
1. As far as I can tell, for the individual files the copyright stays at when the markdown doc was generated, while only the site's copyright is $CURRENT_YEAR. Do you have a specific area you saw that needed changing?
2. I assume people who would care enough would be able to change this themselves? I personally find the current defaults pretty decent and applicable
3. Yeah definitely, gotta give the creator credit lol

**Comment by kevin51jiang** [comment]
Hey @leebyron just pinging to see if you're still interested :)

**Comment by leebyron** [comment]
Sorry for letting this sit for so long, but I appreciate your support and help! I tried to amend to this branch but hit some snags so I pulled your commits directly over to #5 so I could rebase and amend.

**Pull request closed without merging**
